### ISSUE TITLE
Can not pass Menu service into another service

### ISSUE THREAD

**Issue by davidkudera** [Carrooi/Nette-Menu#16]
``` yaml
extensions:
  menu: DK\Menu\DI\Extension

services:
  App\SomeComponent(@menu.default)
```
