### ISSUE TITLE
How to create item without target/group?

### ISSUE THREAD

**Issue by fmasa** [Carrooi/Nette-Menu#20]
Is there any way to create item w/o target? Consider this scenario, when _Catalog_ is only used to group several links and there is no such page?
- Catalog
  - Products
  - Categories

**Comment by davidkudera** [comment]
Unfortunatelly it's not possible right now. Currently I just use some other page as target (like products page).

It's definitely not a good solution and I plan to add support for that

**Comment by fistaro** [comment]
It is possible to use javascript:void(); as target, but you have to rewrite code of carrooi menu to catch javascript: as new type of target.

**Comment by davidkudera** [comment]
With 2.0.0 you don't need to specify any link or action in which case `#` will be used as a link. Or you can specify your own link with the `link` option:

```yaml
Catalog:
  link: 'javascript:void();'
  items:
    Products:
      action: :Products:default
    Categories:
      action: :Categories:default
```
