### ISSUE TITLE
Service 'menu.component.menu' has already been added.

### ISSUE THREAD

**Issue by webrouse** [Carrooi/Nette-Menu#25]
Hi,

I have installed the latest version 2.0.

I created a configuration like in the example:
```yaml
menu:
  front:
    items:
      Home:
        action: :Front:Home:default
      Books:
        link: '#'
        items:
          All:
            action: :Front:Books:all
          Featured:
            action: :Front:Books:featured
  admin:
    items:
      Users:
        action: :Admin:Users:default
      Books:
        action: :Admin:Books:default
```

And I receive error: **Service 'menu.component.menu' has already been added.**
[----> Tracy report <----](https://github.com/Carrooi/Nette-Menu/files/1245435/tracy.zip)

The problem is probably resolved by commit: [2324df0a506748585b55c76c4656f0289a5a2953](https://github.com/Carrooi/Nette-Menu/commit/2324df0a506748585b55c76c4656f0289a5a2953)

**Do you plan release a new stable version that fixes the bug?**

I went according to the example and it would not work. 
If I only started with Nette, I would probably have tried some other extension right away. 

**It would help to add some tests of DI extension
to prevent such bugs (I can prepare PR if you are interested).**

I've been using your extension for a long time, and it's a very good thing!
