### ISSUE TITLE
"include" item setting

### ISSUE THREAD

**Issue by tg666** [Carrooi/Nette-Menu#29]
Hi,
I like new version (^2.0.0) of this package, implementation is much better now. Good job :+1: 
But I miss setting `include` on items e.g.
```yaml
menu:
    MyMenu:
        items:
            LinkOne:
                action: :Module:Presenter:default
                include: '^Module\:Presenter\:[a-zA-Z\:]+$'
```
Is there any reason why this is not in version 2?
Thanks for your time :slightly_smiling_face:
