### ISSUE TITLE
Link generator doesn't work when modules are used

### ISSUE THREAD

**Issue by foxycode** [Carrooi/Nette-Menu#33]
I found problem with my last PR https://github.com/Carrooi/Nette-Menu/pull/32

Everything was ok, until I needed to use it in application with modules. On homepage, which is not in module everythong seems ok, but when I enter any presenter under module, `LinkGenerator` tries to create link under current module, instead of global namespace.

Error:
```
Invalid link: Cannot load presenter 'Stats:Overview', class 'App\StatsModule\Presenters\OverviewPresenter' was not found. 
```

Menu:
```yaml
menu:
    default:
        items:
            overview:
                title: Přehled
                action: Overview:default
            stats:
                title: Statistiky
                action: Stats:AccountBalance:default
                include: ^Stats.*\:.+$

```

Of course I tried to fix it, but I wasn't able. I always thought that `LinkGenerator` is creating links from"top-level" every time. I also wasn't able to add failing test, because this need integration test.

Any ideas?
